services:

    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: afifa-wedding-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - wedding
    db:
        image: postgres:15
        container_name: afifa-wedding-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5442:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - wedding

    nginx:
        image: nginx:alpine
        container_name: afifa-wedding-nginx
        ports:
            - "83:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - wedding

    redis:
        image: redis:latest
        container_name: afifa-wedding-redis
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        ports:
            - "6383:6379"
        volumes:
            - ./redisdata:/data
        networks:
            - wedding
volumes:
    pgdata:

networks:
    wedding:
